security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        api_user_provider:
            entity:
                class: App\Infrastructure\Security\ApiKey\ApiKey
                property: key
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/api
            provider: api_user_provider
            stateless: true
            custom_authenticators:
                - App\Infrastructure\Security\ApiKey\ApiKeyAuthenticator

    access_control:
         - { path: ^/api, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
