parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude: '../src/{Infrastructure/Migrations,Infrastructure/Kernel.php}'

    App\Infrastructure\Controller\Api\:
        resource: '../src/Infrastructure/Controller/Api'
        tags: ['controller.service_arguments']

    App\Infrastructure\EventListener\QuotaListener:
        tags:
            - { name: kernel.event_listener, event: kernel.response }

    App\Infrastructure\Services\LaBonneBoite\LaBonneBoiteClient:
        bind:
            $clientId: '%env(LA_BONNE_BOITE_CLIENT_ID)%'
            $clientSecret: '%env(LA_BONNE_BOITE_CLIENT_SECRET)%'